<?php
/** @var \BinaryAnvil\Customer\Block\AccountData $block */

$savedAddress = $block->getSavedAddress();
$savedAddressUrl = $block->getAddressEditUrl();
$recentOrderData = $block->getRecentOrderData();

$customerData = $block->getCustomerData();
$editUrl = $block->getCustomerEditUrl();
?>

<?php // TODO: work for backend - insert right edit redirect ?>

<?php if (!$recentOrderData): ?>
    <div class="block block-dashboard-orders">
        <div class="block-title order">
            <strong><?= __('Recent Orders') ?></strong>
        </div>
        <div class="block-content">
            <div class="table-wrapper orders-recent bk">
                <table class="data table table-order-items recent" id="my-orders-table">
                    <caption class="table-caption"><?= __('Recent Orders') ?></caption>
                    <thead>
                    <tr>
                        <th scope="col" class="col id"><?= __('Order Number:') ?></th>
                        <th scope="col" class="col date"><?= __('Date Ordered:') ?></th>
                        <th scope="col" class="col status"><?= __('Status:') ?></th>
                        <th scope="col" class="col actions"><?= __('Details:') ?></th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <td data-th="<?= $block->escapeHtml(__('None')) ?>" class="col id"><?= __('None') ?>.</td>

                    </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
<?php endif; ?>

<div class="container-box">
    <div class="wrap">
        <div class="header-items">
            <span><?= __('My Profile') ?></span>
        </div>
        <div class="box-function">
            <div class="header-name"><span><?= __('Account Info') ?></span></div>
            <div class="content">
                <ul>
                    <li><span class="title"><?= __('Name') ?>: </span>
                        <span class="value"><?= $customerData['name'] ?></span>
                    </li>
                    <li><span class="title"><?= __('Email') ?>: </span>
                        <span class="value"><?= $customerData['email'] ?></span>
                    </li>
                </ul>
            </div>
            <div class="buttom">
                <a href="<?= $editUrl ?>"><?= __('Edit') ?></a>
            </div>
        </div>
    </div>
</div>

<div class="container-box">
    <div class="wrap">
        <div class="header-items">
            <span class="hidden"><?= __('saved addresses') ?></span>
        </div>
        <div class="box-function">
            <div class="header-name"><span><?= __('saved addresses') ?></span></div>
            <div class="content">
                <?php if ($savedAddress): ?>
                    <?= $savedAddress ?>
                <?php else: ?>
                    <span>None</span>
                <?php endif; ?>
            </div>
            <div class="buttom">
                <a href="<?= $savedAddressUrl; ?>"><?= __('Edit') ?></a>
            </div>
        </div>
    </div>
</div>

<div class="container-box">
    <div class="wrap">
        <div class="header-items">
            <span class="hidden"><?= __('My local retailer') ?></span>
        </div>
        <div class="box-function">
            <div class="header-name"><span><?= __('My local retailer') ?></span></div>
            <div class="content">
                <?php
                $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
                $resource = $objectManager->get('Magento\Framework\App\ResourceConnection');
                $connection = $resource->getConnection();
                $tableName = $resource->getTableName('local_retailer_store');

                $customerSession = $objectManager->create('Magento\Customer\Model\Session');
                $getIdcus = $customerSession->getCustomerId();

                $sql = "Select * FROM " . $tableName . " WHERE id_customer_use =" . $getIdcus;
                $array_customer = $connection->fetchAll($sql);
                if (!empty($array_customer)) {
                    foreach ($array_customer as $key) {
                        $storeName = $key['store_name'];
                        $street = $key['street'];
                        $city = $key['city'];
                        $state = $key['state'];
                        $zip = $key['zip'];
                        break;
                    } ?>
                    <?= $storeName; ?></br>
                    <?= $street; ?></br>
                    <?= $city; ?>, <?= $state; ?>, <?= $zip; ?>
                <?php } else { ?>
                    <span>None</span>
                <?php } ?>
            </div>
            <div class="buttom">
                <a href="/customer/account/edit#main-local-retails"><?= __('Edit') ?></a>
            </div>
        </div>
    </div>
</div>

<div class="container-box">
    <div class="wrap">
        <div class="header-items">
            <span><?= __('Payments') ?></span>
        </div>
        <div class="box-function">
            <div class="header-name save-payment-mobile"><span><?= __('Saved Payments') ?></span></div>
            <?= $block->getChildHtml('my_account_payments_data') ?>
            <div class="buttom">
                <a href="<?= $block->getUrl('customer/paymentinfo') ?>"><?= __('Edit') ?></a>
            </div>
        </div>
    </div>
</div>