<?php

?>
<?php
/** @var Magento\Catalog\Block\Product\ListProduct $block */
$wishlistHelper = $this->helper('Magento\Wishlist\Helper\Data');
$helper = $this->helper('Magento\Catalog\Helper\Output');
$collection = $wishlistHelper->getWishlistItemCollection();

$image = 'category_page_grid';
$countBreak = 0;
?>

<div class="container-wishlist container">
    <h3><?= __('Wishlist')?></h3>
    <?php if (count($collection)) :?>
    <ol class="products list items product-items">
        <?php foreach ($collection as $item) : ?>
            <?php
            $_product = $item->getProduct();
            ?>
            <li class="item product product-item <?php if (!$_product->isSaleable()): ?>hidden<?php endif; ?>">
                <div class="product-item-info" data-container="product-grid">
                    <?php
                    $_imagehelper = $this->helper('Magento\Catalog\Helper\Image');
                    $productImage = $_imagehelper->init($_product, $image)->constrainOnly(FALSE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->getUrl();
                    ?>

                    <?php // Product Image ?>
                    <a title="<?= __('Go to') ?> <?= $helper->productAttribute($_product, $_product->getName(), 'name'); ?>"
                       href="<?= $_product->getProductUrl() ?>"
                       class="product photo product-item-photo"
                    >
                        <img class="photo image" src="<?= $productImage ?>" alt="<?= $helper->productAttribute($_product, $_product->getName(), 'name'); ?>" />
                    </a>

                    <div class="product details product-item-details">
                        <strong class="product name product-item-name">
                            <a class="product-item-link"
                               href="<?= $_product->getProductUrl() ?>"
                               title="<?= $helper->productAttribute($_product, $_product->getName(), 'name'); ?>"
                            >
                                <?= $helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                            </a>
                        </strong>
                        <?= $block->getProductPrice($_product)?>

                        <?php if ($_product->isSaleable()): ?>
                            <div class="product-item-actions">
                                <div class="actions-primary-wishlist">
                                    <a href="<?= $_product->getProductUrl() ?>">
                                    <button type="button" data-role="tocart" title="<?= $block->escapeHtmlAttr(__('Add to Cart')) ?>" class="action tocart primary-wishlist">
                                        + <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                                    </button>
                                    </a>
                                </div>
                            </div>
                        <?php else: ?>
                            <?php if ($_product->getIsSalable()): ?>
                                <p class="available stock" title="<?= $block->escapeHtmlAttr(__('Availability')) ?>">
                                    <span><?= $block->escapeHtml(__('In stock')) ?></span>
                                </p>
                            <?php else: ?>
                                <p class="unavailable stock" title="<?= $block->escapeHtmlAttr(__('Availability')) ?>">
                                    <span><?= $block->escapeHtml(__('no longer available')) ?></span>
                                </p>
                            <?php endif; ?>
                        <?php endif; ?>
                    </div>
                </div>
            </li>
        <?php $countBreak = $countBreak +1; if($countBreak == 6 ) { break;} ?>    
        <?php endforeach; ?>
    </ol>
    <a href="<?= $block->getBaseUrl(); ?>wishlist" class="view-wishlist"><span><?= __('View wishlist')?></span></a>
<?php else: ?>
    <div class="message info empty">
        <span class="emty-wishlist"><?= $block->escapeHtml(__('Engage in retail therapy. Go buy something.')) ?></span>
        <a href="<?= $block->getBaseUrl(); ?>"><span><?= __('Fill your wishlist')?></span></a>
    </div>
<?php endif; ?>
</div>


<!-- <script type="text/x-magento-init">
    {
        "*": {
            "Magento_Customer/js/wishlist-height": {
                "imageContainer": ".container-wishlist .product-item .product-item-photo",
                "productName": ".container-wishlist .product-item .product-item-name"
            }
        }
    }
</script>
 -->