<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var \Magento\Theme\Block\Html\Header\Logo $block
 */
?>
<?php $storeName = $block->getThemeName() ? $block->getThemeName() : $block->getLogoAlt(); ?>
<div class="nav-toggle-wrap">
    <span data-action="toggle-nav" class="action nav-toggle">
        <span></span>
    </span>
    <i id="ic-search-mobi" class="search-icon icon-elo-search"></i>
</div>

<?php if ($block->isHomePage()) { ?>
<strong class="logo">
    <?php } else { ?>
    <a class="logo" href="<?= $block->getUrl('') ?>" title="<?= $storeName ?>">
        <?php } ?>

        <img src="<?= $block->getLogoSrc() ?>"
             alt="<?= $block->getLogoAlt() ?>"
            <?= $block->getLogoWidth() ? 'width="' . $block->getLogoWidth() . '"' : '' ?>
            <?= $block->getLogoHeight() ? 'height="' . $block->getLogoHeight() . '"' : '' ?>
        />

        <?php if ($block->isHomePage()) { ?>
</strong>
<?php } else { ?>
    </a>
<?php } ?>

<script type="text/javascript">
    require(['jquery'], function ($) {
        $(document).ready(function () {
            let navInMobile = ".customer-welcome>#PopupLogin>.pop-up-container";

            // click search in mobile
            $('#ic-search-mobi').click(function () {
                $('.block-search .block-content').toggle();
            });

            $(document).mouseup(function (e) {
                let container = $(navInMobile);
                let toggleButton = $('.action.nav-toggle');

                // if the target of the click isn't the container nor a descendant of the container
                if (!container.is(e.target) && container.has(e.target).length === 0
                    && !toggleButton.is(e.target) && toggleButton.has(e.target).length === 0 ) {
                    $('html').removeClass('nav-before-open nav-open');
                }
            });

        })
    });
</script>