<?php
/** @var \Magento\Customer\Block\Form\Login $block */
?>

<div class="block block-customer-login">
    <?php /**
     * <div class="block-title">
     * <strong id="block-customer-login-heading" role="heading" aria-level="2">
     * <?= $block->escapeHtml(__('Returning Customers')) ?>
     * </strong>
     * </div>
     **/ ?>

    <div class="block-content" aria-labelledby="block-customer-login-heading">
        <form class="form form-login"
              action="<?= $block->escapeUrl($block->getPostActionUrl()) ?>"
              method="post"
              id="login-form"
              data-mage-init='{"validation":{}}'>
            <?= $block->getBlockHtml('formkey') ?>
            <fieldset class="fieldset login">
                <!-- <div class="field note">If you are a registered user, please enter your email and password.</div>-->
                <div class="field header">I am already a customer.</div>

                <div class="field email required">
                    <label class="label" for="email"><span><?= $block->escapeHtml(__('Email')) ?></span></label>
                    <div class="control">
                        <input name="login[username]"
                               value="<?= $block->escapeHtmlAttr($block->getUsername()) ?>" <?php if ($block->isAutocompleteDisabled()): ?> autocomplete="off"<?php endif; ?>
                               id="email" type="email" class="input-text"
                               title="<?= $block->escapeHtmlAttr(__('Email')) ?>"
                               data-validate="{required:true, 'validate-email':true}">
                    </div>
                </div>

                <div class="field password required">
                    <label for="pass" class="label"><span><?= $block->escapeHtml(__('Password')) ?></span></label>
                    <div class="control">
                        <input name="login[password]"
                               type="password" <?php if ($block->isAutocompleteDisabled()): ?> autocomplete="off"<?php endif; ?>
                               class="input-text" id="pass" title="<?= $block->escapeHtmlAttr(__('Password')) ?>"
                               data-validate="{required:true}">
                    </div>
                </div>

                <?php // echo $block->getChildHtml('form_additional_info') ?>

                <div class="actions-toolbar">
                    <div class="third checkbox-field">
                        <input type="checkbox" name="remember_me" id="Login_Remember_Me"/>
                        <label for="Login_Remember_Me" data-name="remember_me"><span>Remember me.</span></label>
                    </div>

                    <div class="secondary">
                        <a class="action remind" href="<?= $block->escapeUrl($block->getForgotPasswordUrl()) ?>">
                            <span><?= $block->escapeHtml(__('Forgot Your Password?')) ?></span>
                        </a>
                    </div>
                    <div class="primary">
                        <button type="submit" class="action login primary" name="send" id="send2">
                            <span><?= $block->escapeHtml(__('Login')) ?></span></button>
                    </div>
                </div>


                <?= $block->getChildHtml('federation.facebook.button') ?>

                <?= $block->getChildHtml('social-login-popup-authentication-social-login') ?>


                <!-- <div class="brand-button gg">-->
                <!--  <div class="c1"></div>-->
                <!--  <div class="c2">SIGN UP WITH GOOGLE</div>-->
                <!--  </div>-->


            </fieldset>
        </form>
    </div>
</div>

<script>
    require([
        'jquery',
        'domReady!'
    ], function ($) {
        $(document).ready(function () {
            // Click label and check/uncheck radio or checkbox
            $('.checkbox-field label').click(function () {
                // console.log(".");
                let _this = $(this);
                let _for = _this.prop('for');
                let name = _this.attr('data-name');
                if (_for !== "" && name !== "") {
                    jQuery('input[name=' + name + ']').trigger('click');
                }
            });
        });
    });
</script>