<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * Product additional attributes template
 *
 * @var $block \Magento\Catalog\Block\Product\View\Attributes
 */
?>
<?php
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$_product = $block->getProduct();
?>
<?php if ($_additional = $block->getAdditionalData()): ?>
    <div class="additional-attributes-wrapper table-wrapper">
        <div class="data table additional-attributes" id="product-attribute-specs-table">
        <!-- <caption class="table-caption">SPECIFICATIONS</caption>-->
            <div class="spec-wrapper">
            <?php foreach ($_additional as $_data): ?>
                <div class="spec-item">
                    <div class="label"><?= $block->escapeHtml(__($_data['label'])) ?></div>
                    <div class="data" data-th="<?= $block->escapeHtml(__($_data['label'])) ?>">
                        <?= $_helper->productAttribute($_product, $_data['value'], $_data['code']) ?>
                    </div>
                </div>
            <?php endforeach; ?>
            </div>
        </div>
    </div>
<?php endif;?>
