<div class="on-top-header one-col">
    <div class="on-top-header-inner">
        <?= $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('on_top_header')->toHtml(); ?>
        <i class="far fa-times" id="closeTopHeader"></i>
    </div>
</div>

<script type="text/javascript">
    require(['jquery', 'jquery/ui'], function ($) {
        $(document).ready(function(){
            // sticky menu
            function checkSticky() {
                let header = $('header.page-header');
                let currentTop = jQuery(window).scrollTop();
                if (currentTop > 40) {
                    header.addClass("sticky");
                } else {
                    header.removeClass("sticky");
                }
            }

            $(window).scroll(function () {
                checkSticky();
            });

            checkSticky();

            $('#closeTopHeader').click(function () {
                $('.on-top-header').hide();
            });
        });
    });
</script>