<?php
// @codingStandardsIgnoreFile
/** @var Magento\Customer\Block\Account\Customer $block */
?>

<?php if ($block->customerLoggedIn()): ?>

    <li class="customer-welcome loggedIn" data-block="customer-block">
        <span class="customer-name"
              role="link"
              tabindex="0"
              data-trigger-keypress-button="true"
              data-bind="scope: 'customer'">
            <span class="customer-txt">Hello</span><span>&nbsp;</span><span
                    data-bind="text: customer().firstname"></span>
        </span>

        <script type="text/x-magento-init">
        {
            "*": {
                "Magento_Ui/js/core/app": {
                    "components": {
                        "customer": {
                            "component": "Magento_Customer/js/view/customer"
                        }
                    }
                }
            }
        }
        </script>

        <div class="customer-menu">
            <ul id="drop-my-account" style="display: none">
                <li>
                    <a href="<?= $block->getUrl('customer/account/'); ?>" title="My Account">
                        My Account
                    </a>
                </li>
                <li>
                    <a href="<?= $block->getUrl('sales/order/history/'); ?>" title="My Orders">
                        My Orders
                    </a>
                </li>
                <li>
                    <a href="<?= $block->getUrl('faqs/'); ?>" title="FAQS">
                        FAQS
                    </a>
                </li>
                <li>
                    <a href="<?= $block->getUrl('customer/account/logout/'); ?>" title="Sign Out">
                        Sign Out
                    </a>
                </li>
            </ul>
        </div>
    </li>


<?php else: ?>
    <li class="customer-welcome" data-block="customer-block">
        <span class="customer-name"
              role="link"
              tabindex="0"
              data-trigger-keypress-button="true"
              data-bind="scope: 'customer'">
            <span class="customer-txt">LOGIN/SIGN UP</span>
        </span>

        <script type="text/x-magento-init">
        {
            "*": {
                "Magento_Ui/js/core/app": {
                    "components": {
                        "customer": {
                            "component": "Magento_Customer/js/view/customer"
                        }
                    }
                }
            }
        }
        </script>

        <!--        <div class="customer-menu2">-->
        <div id="PopupLogin" class="fixed-pop-up" style="display: none">

            <div class="pop-up-container">
                <i class="far fa-times" id="closePopupLogin"></i>
                <?= $block->getChildHtml('customer_form_login'); ?>
                <div class="register">
                    <div class="register-inner">
                        <div class="dercor-line-black"></div>
                        <div class="field header">SIGN UP</div>
                        <p>Create an account: see your order history, check out faster, save your favorite items and get
                            the latest news about Infinity by Cherokee.
                        </p>
                        <a id="btn-create-account" class="create-an-account" title="Create an Account"
                           href="javascript:void(0);">CREATE AN ACCOUNT</a>
                    </div>
                </div>
            </div>
        </div>
        <!--        </div>-->


        <div id="PopupRegister" class="fixed-pop-up" style="display: none">

            <div class="pop-up-container">
                <i class="far fa-times" id="closePopupLogin"></i>
                <?= $block->getChildHtml('customer_form_register'); ?>
                <div class="register">
                    <div class="register-inner">

                        <div class="dercor-line-black"></div>
                        <div class="field header">ALREADY HAVE AN ACCOUNT?</div>
                        <a id="btn-login-account" class="create-an-account" title="Sign in"
                           href="javascript:void(0);">SIGN IN</a>
                    </div>
                </div>
            </div>
        </div>

    </li>

<?php endif; ?>

<script>
    require(['jquery', 'matchMedia'], function ($, mediaCheck) {
        var listItem = $('li.customer-welcome');
        mediaCheck({
            media: '(max-width: 767px)',
            entry: function () {
                listItem.attr('data-block', "");
            },
            exit: function () {
                listItem.attr('data-block', "customer-block");
            }
        });

        // Thien
        $('body').on('click', '.customer-welcome>.customer-name', function () {
            $('.customer-welcome>#PopupLogin').show();
            $('.customer-welcome>#PopupLogin>.pop-up-container').show();
        });

        $('body').on('click', '#closePopupLogin', function () {
            $('.customer-welcome>#PopupLogin').hide();
            $('.customer-welcome>#PopupLogin>.pop-up-container').hide();
            $('.customer-welcome>#PopupRegister').hide();
            $('.customer-welcome>#PopupRegister>.pop-up-container').hide();
        });


        $(document).click(function (e) {

            if ($(e.target).closest(".customer-welcome>#PopupLogin>.pop-up-container").length > 0
                || $(e.target).closest(".customer-welcome>#PopupRegister>.pop-up-container").length > 0) {

            } else {
                $('.customer-welcome>#PopupLogin').hide();
                $('.customer-welcome>#PopupLogin>.pop-up-container').hide();
                $('.customer-welcome>#PopupRegister').hide();
                $('.customer-welcome>#PopupRegister>.pop-up-container').hide();
            }
        });
        $(document).click(function (e) {

            if ($(e.target).closest(".customer-welcome>.customer-name").length > 0) {
                $('.customer-welcome>#PopupLogin').show();
                $('.customer-welcome>#PopupLogin>.pop-up-container').show();
            }
        });


        $('body').on('click', '#btn-create-account', function () {
            $('.customer-welcome>#PopupRegister').show();
            $('.customer-welcome>#PopupRegister>.pop-up-container').show();
            $('.customer-welcome>#PopupLogin').hide();
            $('.customer-welcome>#PopupLogin>.pop-up-container').hide();
        });

        $('body').on('click', '#btn-login-account', function () {
            $('.customer-welcome>#PopupLogin').show();
            $('.customer-welcome>#PopupLogin>.pop-up-container').show();
            $('.customer-welcome>#PopupRegister').hide();
            $('.customer-welcome>#PopupRegister>.pop-up-container').hide();
        });


        $(document).click(function (e) {
            if ($(e.target).closest(".customer-welcome>.customer-menu>#drop-my-account").length > 0) {
            } else {
                $('.customer-welcome>.customer-menu>#drop-my-account').hide();
                $('.customer-welcome>.customer-name').removeClass("active");

            }
        });
        $(document).click(function (e) {
            if ($(e.target).closest(".customer-welcome>.customer-name").length > 0) {
                //    if($('body').hasClass("customer-menu")){
                $('.customer-welcome #drop-my-account').show();
                $('.customer-welcome>.customer-name').addClass("active");
                //    }
            }
        });


        $('body').on('click', '.block-search>.search-icon', function () {
            $(".block-search>.block-content").toggle();

        });

    });
</script>
