<?php
/** @noinspection PhpUnhandledExceptionInspection */
/** @noinspection SqlNoDataSourceInspection */
/** @noinspection PhpUndefinedMethodInspection */

// @codingStandardsIgnoreFile
/** @var Magento\Customer\Block\Form\Edit $block */

/** @var BinaryAnvil\Customer\Helper\Data $dataHelper */
$dataHelper = $this->helper(\BinaryAnvil\Customer\Helper\Data::class);

$customer = $block->getCustomer();
$customAttributes = $customer->getCustomAttributes();

?>
<form class="form form-edit-account" action="<?= $block->getUrl('customer/account/editPost') ?>" method="post"
      id="form-validate" enctype="multipart/form-data"
      data-hasrequired="<?=
      __('* Required Fields') ?>" autocomplete="off">
    <?= $block->getBlockHtml('formkey') ?>
    <fieldset class="fieldset name">
        <div class="field name required" data-container="change-name">
            <div class="wrap">
                <div class="col lable"><span><?= __('Name'); ?></span></div>
                <div class="col value"><?= $block->escapeHtml($customer->getFirstName() . ' ' . $customer->getLastName()) ?></div>
                <div class="col action"><a href="#"><?= __('Edit'); ?></a></div>
            </div>
            <div class="content">
                <div class="title"><span><?= __('Name'); ?></span>
                    <button class="action cancel" title="<?= __('Edit') ?>">Edit</button>
                </div>
                <div class="content-details">
                    <?= $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Name')->setObject($block->getCustomer())->toHtml() ?>
                    <div class="primary">
                        <button type="submit" class="action save primary" title="<?= __('Save') ?>">
                            <span><?= __('Save Changes') ?></span>
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </fieldset>

    <fieldset class="fieldset email">
        <div class="field email required" data-container="change-email">
            <div class="wrap">
                <div class="col lable"><span><?= __('Email'); ?></span></div>
                <div class="col value"><?= $block->escapeHtml($customer->getEmail()) ?></div>
                <div class="col action"><a href="#"><?= __('Edit'); ?></a></div>
            </div>
            <div class="content">
                <div class="title"><span><?= __('Email'); ?></span>
                    <button class="action cancel" title="<?= __('Edit') ?>">Edit</button>
                </div>
                <div class="content-details">
                    <label class="label" for="email"><span><?= __('Email') ?></span></label>
                    <div class="control">
                        <input type="email" autocomplete="email" name="email" id="email" data-input="change-email"
                               value="<?= $block->escapeHtml($customer->getEmail()) ?>"
                               title="<?= __('Email') ?>"
                               class="input-text" data-validate="{required:true, 'validate-email':true}"/>
                    </div>
                    <div class="field choice">
                        <input type="checkbox" name="change_email" id="change-email" data-role="change-email" value="1"
                               title="<?= $block->escapeHtmlAttr('Change Email') ?>" class="checkbox"/>
                        <label class="label"
                               for="change-email"><span><?= $block->escapeHtml('Change Email') ?></span></label>
                    </div>
                    <div class="primary">
                        <button type="submit" class="action save primary" title="<?= __('Save') ?>">
                            <span><?= __('Save Changes') ?></span>
                        </button>
                    </div>
                </div>
                <div></div>
            </div>
        </div>
    </fieldset>

    <?= $block->getChildHtml('form_fields_before_in_form') ?>
    <fieldset class="fieldset password">
        <div class="field password" data-container="change-email-password">
            <div class="wrap">
                <div class="col lable"><span><?= __('Password'); ?></span></div>
                <div class="col value"><span><?= __('**********'); ?></span></div>
                <div class="col action"><a href="#"><?= __('Edit'); ?></a></div>
            </div>
            <div class="content">
                <div class="title"><span><?= __('Password'); ?></span>
                    <button class="action cancel" title="<?= __('Edit') ?>">Edit</button>
                </div>
                <div class="content-details">
                    <div class="field password current required">
                        <label class="label" for="current-password"><span><?= __('Current Password') ?></span></label>
                        <div class="control">
                            <input type="password" class="input-text" name="current_password" id="current-password"
                                   data-input="current-password" autocomplete="off"/>
                        </div>
                    </div>
                    <div class="field new password required" data-container="new-password">
                        <label class="label" for="password"><span><?= __('New Password') ?></span></label>
                        <div class="control">
                            <input type="password" class="input-text" name="password" id="password"
                                   data-password-min-length="<?= $block->escapeHtml($block->getMinimumPasswordLength()) ?>"
                                   data-password-min-character-sets="<?= $block->escapeHtml($block->getRequiredCharacterClassesNumber()) ?>"
                                   data-input="new-password"
                                   data-validate="{required:true, 'validate-customer-password':true}"
                                   autocomplete="off"/>
                            <div id="password-strength-meter-container" data-role="password-strength-meter"
                                 aria-live="polite">
                                <div id="password-strength-meter" class="password-strength-meter">
                                    <?= __('Password Strength') ?>:
                                    <span id="password-strength-meter-label" data-role="password-strength-meter-label">
                                        <?= __('No Password') ?>
                                    </span>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="field confirm password required" data-container="confirm-password">
                        <label class="label" for="password-confirmation"><span><?=
                                __('Confirm New Password') ?></span></label>
                        <div class="control">
                            <input type="password" class="input-text" name="password_confirmation"
                                   id="password-confirmation"
                                   data-input="confirm-password"
                                   autocomplete="off"/>
                        </div>
                    </div>
                    <div class="field choice">
                        <input type="checkbox" name="change_password" id="change-password" data-role="change-password"
                               value="1"
                               title="<?= $block->escapeHtmlAttr(__('Change Password')) ?>"
                            <?php if ($block->getChangePassword()): ?> checked="checked"<?php endif; ?>
                               class="checkbox"/>
                        <label class="label" for="change-password">
                            <span><?= $block->escapeHtml(__('Change Password')) ?></span>
                        </label>
                    </div>
                    <div class="primary">
                        <button type="submit" class="action save primary" title="<?= __('Save') ?>">
                            <span><?= __('Save Changes') ?></span>
                        </button>
                    </div>
                </div>
                <div></div>
            </div>
            <?= $block->getChildHtml('form_additional_info') ?>
        </div>
    </fieldset>

    <!-- Custom fields -->
    <fieldset class="fieldset custom-fields">
        <div class="field custom-fields-inner">
            <div class="wrap">
                <div class="col lable"><span><?= __('Custom Fields'); ?></span></div>
                <div class="col value"></div>
                <div class="col action"><a href="#"><?= __('Edit'); ?></a></div>
            </div>
            <div class="content">
                <div class="title"><span><?= __('Custom Fields'); ?></span>
                    <button class="action cancel" title="<?= __('Edit') ?>">Edit</button>
                </div>
                <div class="content-details">

                    <!-- Gender Field -->
                    <div class="field">
                        <?php $genders = $dataHelper->getCustomerGenderOptions() ?>
                        <label class="label" for="gender"><span><?= __('Gender') ?></span></label>
                        <select autocomplete="gender" name="gender" id="gender" data-input="change-gender"
                                title="<?= __('Gender') ?>" class="select" data-validate="{required:true}">
                            <?php foreach ($genders as $gender): ?>
                                <option value="<?= $gender['value'] ?>"
                                    <?php if ($gender['value'] == $customer->getGender()) echo ' selected' ?>>
                                    <?= __($gender['label']) ?>
                                </option>
                            <?php endforeach ?>
                        </select>
                    </div>


                    <!-- Select Fields -->
                    <?php
                    $selectFields = [
                        $dataHelper::CUSTOMER_TOP_SIZE_ATTRIBUTE_CODE => "Top Size",
                        $dataHelper::CUSTOMER_BOTTOM_SIZE_ATTRIBUTE_CODE => "Bottom Size",
                        $dataHelper::CUSTOMER_SHOE_SIZE_ATTRIBUTE_CODE => "Shoe Size",
                        $dataHelper::CUSTOMER_UNDER_SCRUB_SIZE_ATTRIBUTE_CODE => "Underscrub Size",
                        $dataHelper::CUSTOMER_BOTTOM_LENGTH_ATTRIBUTE_CODE => "Bottom Length",
                        $dataHelper::CUSTOMER_COLOR_PREFERENCE_ATTRIBUTE_CODE => "Color Preference",
                        $dataHelper::CUSTOMER_SCRUB_HABITS_ATTRIBUTE_CODE => "Scrub Habits",
                        $dataHelper::CUSTOMER_JACKET_SIZE_ATTRIBUTE_CODE => "Jacket Size",
                        $dataHelper::CUSTOMER_COLOR_CODE_WORKSPACE_ATTRIBUTE_CODE => "Color-coded Workplace",
                        $dataHelper::CUSTOMER_PREFER_WAY_OF_SHOP_ATTRIBUTE_CODE => "Preferred Way Of Shopping",
                        $dataHelper::CUSTOMER_DAISY_AWARD_WINNER_ATTRIBUTE_CODE => "Daisy Award Winner"
                    ];
                    ?>

                    <?php foreach ($selectFields as $optionKey => $optionName) {
                        $customField = $dataHelper->getCustomerOptionsByAttributeCode($optionKey);
                        $currentOption = $customAttributes[$optionKey];
                        if ($customField && $optionKey) {
                        ?>
                        <div class="field select">
                            <label class="label" for="<?= $optionKey ?>"><span><?= $optionName ?></span></label>
                            <select autocomplete="<?= $optionKey ?>" name="<?= $optionKey ?>" id="<?= $optionKey ?>"
                                    title="<?= $optionName ?>" class="select">
                                <?php foreach ($customField as $option): ?>
                                    <option value="<?= $option['value'] ?>"
                                        <?php if ($option['value'] == $currentOption->getValue()) echo ' selected' ?>>
                                        <?= $option['label'] ?>
                                    </option>
                                <?php endforeach ?>
                            </select>
                        </div>
                        <?php } ?>
                    <?php } ?>
                    <!-- # Select Fields -->

                    <!-- Primary Place of Work -->
                    <?php
                        $placeOfWork = $customer->getCustomAttribute($dataHelper::CUSTOMER_PLACE_OF_WORK_ATTRIBUTE_CODE);
                        $placeOfWorkVal = $placeOfWork ? $placeOfWork->getValue() : "";
                    ?>
                    <div class="field text">
                        <label class="label" for="place_of_work"><span>Primary Place of Work</span></label>
                        <input type="text" name="place_of_work" value="<?= $placeOfWorkVal ?>" />
                    </div>

                    <!-- Date Of Bird -->
                    <?php /**
                    <div class="field dob">
                        <div class="control">
                            <?php $_dob = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Dob') ?>
                            <?php if ($_dob->isEnabled()): ?>
                                <?= $_dob->setDate($block->getCustomer()->getDob())->toHtml() ?>
                            <?php endif ?>
                        </div>
                    </div> */ ?>

                    <div class="primary">
                        <button type="submit" class="action save primary" title="<?= __('Save') ?>">
                            <span><?= __('Save Changes') ?></span>
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </fieldset>


    <script type="text/javascript">
        require([
            "jquery",
            "mage/mage"
        ], function ($) {

        });
    </script>

    <!-- # Custom fields -->
</form>

<script type="text/javascript">
    require([
        "jquery",
        "mage/mage"
    ], function ($) {
        let dataForm = $('#form-validate');
        let ignore = null;

        dataForm.mage('validation', {
            ignore: ignore ? ':hidden:not(' + ignore + ')' : ':hidden'
        });

    });
</script>

<script type="text/x-magento-init">
    {
        "[data-role=change-email], [data-role=change-password]": {
            "changeEmailPassword": {
                "titleChangeEmail": "Change Email",
                "titleChangePassword": "Change Password",
                "titleChangeEmailAndPassword": "Change Email and Password"
            }
        },
        "[data-container=new-password]": {
            "passwordStrengthIndicator": {
                "formSelector": "form.form-edit-account"
            }
        }
    }
</script>

<script type="text/javascript">
    require(['jquery'], function ($) {
        $(function () {
            $('.wrap a').click(function (e) {
                e.preventDefault();
                let wrapParent = $(this).parent().parent().parent();

                if (wrapParent.hasClass('password')) {
                    $("#change-password").click();
                }
                if (wrapParent.hasClass('email')) {
                    $("#change-email").click();
                }
                wrapParent.find('.wrap').toggle().toggleClass('active');
                wrapParent.find('.content').toggle().toggleClass('active');
            });

            $('.content .cancel').click(function (e) {
                e.preventDefault();
                let wrapParent = $(this).parent().parent().parent().parent();

                if (wrapParent.hasClass('password')) {
                    $("#change-password").click();
                }
                if (wrapParent.hasClass('email')) {
                    $("#change-email").click();
                }
                wrapParent.find('.wrap').toggle().toggleClass('active');
                wrapParent.find('.content').toggle().toggleClass('active');
            });
        });
    });
</script>

<!-- SHIPPING ADDRESS -->
<?php
$_objectManager = \Magento\Framework\App\ObjectManager::getInstance();

/** @var BinaryAnvil\Customer\Block\AccountData $savedAddress */
$savedAddress = $_objectManager->get('BinaryAnvil\Customer\Block\AccountData');
$getAddress = $savedAddress->getSavedAddress();

$customerSession = $_objectManager->create('Magento\Customer\Model\Session');
$getCustomerId = $customerSession->getCustomerId();

$countryList = $savedAddress->getCountries();
$regionList = $savedAddress->getRegion();

// get customer default
$addressInfo = $_objectManager->get('BinaryAnvil\Customer\Block\Addressinfo');
$shippingAddress = $addressInfo->getDefaultShippingAddress();

$idAddress = $firstName = $lastName = $street = $street2 = $city = $country_id = $region_id = $postcode = $telephone = "";

if (isset($shippingAddress)) {
    $changeArray = array();
    $changeArray = $shippingAddress->__toArray();
    // echo "<pre>";print_r($changeArray);
    $idAddress = $changeArray['id'];
    $firstName = $changeArray['firstname'];
    $lastName = $changeArray['lastname'];
    $street = $changeArray['street'][0];
    if (isset($changeArray['street'][1])) {
        $street2 = $changeArray['street'][1];
    }
    $city = $changeArray['city'];
    $country_id = $changeArray['country_id'];
    $region_id = $changeArray['region_id'];
    $postcode = $changeArray['postcode'];
    $telephone = $changeArray['telephone'];
    $customer_id = $changeArray['customer_id'];
}
?>

<div class="save-address" id="defaultshipping">
    <div class="title-address">
        <span>Save addresses</span>
        <a href="javascript:void(0)" class="link-edit-address"><?= __('Edit'); ?></a>
    </div>
    <div class="box-address">
        <div class="content-address">
            <p>
                <?php if ($getAddress): ?>
                    <?= $getAddress ?>
                    <label for="set_shipping_address" class="defaul-shipping"><span>Default address</span></label>
                <?php else: ?>
                    <span>None</span>
                <?php endif; ?>
            </p>
        </div>
        <?php if ($getAddress): ?>
            <div class="content-edit-address">
                <div class="box-edit-address">
                    <form class="form-address-edit" id="<?= $idAddress; ?>"
                          action="<?= $this->getBaseUrl(); ?>customer/address/formPost/id/<?= $idAddress; ?>/"
                          method="post" id="form-validate" enctype="multipart/form-data"
                          data-hasrequired="* Required Fields" novalidate="novalidate">
                        <?= $addressInfo->getBlockHtml('formkey') ?>
                        <div class="content-details">
                            <div class="field field-firstname required">
                                <label class="label" for="name">
                                    <span><?= __('name') ?></span>
                                </label>
                                <div class="control">
                                    <input type="text" id="name" name="firstname" value="<?= $firstName; ?>"
                                           title="Name"
                                           class="input-text required-entry" data-validate="{required:true}"
                                           aria-required="true">
                                </div>
                            </div>
                        </div>
                        <div class="content-details">
                            <div class="field field-lastname required">
                                <label class="label" for="lastname">
                                    <span><?= __('last name') ?></span>
                                </label>
                                <div class="control">
                                    <input type="text" id="lastname" name="lastname" value="<?= $lastName; ?>"
                                           title="Last Name"
                                           class="input-text required-entry" data-validate="{required:true}"
                                           aria-required="true">
                                </div>
                            </div>
                        </div>
                        <div class="content-details">
                            <div class="field field-address required">
                                <label class="label" for="address">
                                    <span><?= __('address') ?></span>
                                </label>
                                <div class="control">
                                    <input type="text" id="street_1" name="street[]" value="<?= $street; ?>"
                                           title="Street Address 1"
                                           class="input-text required-entry" data-validate="{required:true}"
                                           aria-required="true">
                                </div>
                                <?php if (isset($street2)): ?>
                                    <div class="control paddingtop">
                                        <input type="text" id="street_2" name="street[]" value="<?= $street2; ?>"
                                               title="Street Address 2"
                                               class="input-text required-entry" data-validate="{required:true}"
                                               aria-required="true">
                                    </div>
                                <?php else: ?>
                                    <div class="control paddingtop">
                                        <input type="text" id="street_2" name="street[]" value=""
                                               title="Street Address 2"
                                               class="input-text" data-validate="{required:false}"
                                               aria-required="false">
                                    </div>
                                <?php endif; ?>
                            </div>
                        </div>
                        <div class="content-details">
                            <div class="field field-city required">
                                <label class="label" for="city">
                                    <span><?= __('city') ?></span>
                                </label>
                                <div class="control">
                                    <input type="text" id="city" name="city" value="<?= $city; ?>"
                                           title="City" class="input-text required-entry"
                                           data-validate="{required:true}"
                                           aria-required="true">
                                </div>
                            </div>
                        </div>
                        <div class="default-state content-details lx-<?= $idAddress ?>">
                            <div class="field state">
                                <label class="label" for="state">
                                    <span><?= __('state') ?></span>
                                </label>
                                <div class="control">
                                    <?= $regionList; ?>
                                </div>
                            </div>
                        </div>
                        <div class="content-details zip-code">
                            <div class="field field-zip-code required">
                                <label class="label" for="zipcode">
                                    <span><?= __('zip code') ?></span>
                                </label>
                                <div class="control">
                                    <input type="text" id="zip" name="postcode"
                                           value="<?= $postcode; ?>" title="zipcode"
                                           class="input-text validate-zip-international" data-validate="{required:true}"
                                           aria-required="true">
                                </div>
                            </div>
                        </div>
                        <div class="content-details phone">
                            <div class="field field-phone required">
                                <label class="label" for="phone">
                                    <span><?= __('phone') ?></span>
                                </label>
                                <div class="control">
                                    <input type="text" id="telephone" name="telephone" value="<?= $telephone; ?>"
                                           title="phone" class="input-text required-entry"
                                           data-validate="{required:true}"
                                           aria-required="true">
                                </div>
                            </div>
                        </div>
                        <div class="content-details country">
                            <div class="field country">
                                <label class="label" for="country">
                                    <span><?= __('country') ?></span>
                                </label>
                                <div class="control">
                                    <?= $countryList; ?>
                                </div>
                            </div>
                        </div>
                        <div class="content-details country">
                            <div class="checkbox-field-default">
                                <label for="set_shipping_address"><span>Default address</span></label>
                            </div>
                        </div>

                        <div class="primary saved-box">
                            <button type="submit" class="action primary" title="<?= __('Save') ?>">
                                <span><?= __('Save Changes') ?></span>
                            </button>
                        </div>
                    </form>
                </div>
            </div>

            <script type="text/javascript">
                require(['jquery'], function ($) {
                    $(function () {
                        // select state
                        $(".default-state.content-details").find('option').removeAttr("selected");

                        $('.default-state.content-details.lx-<?= $idAddress; ?> .state #state option[value="<?= $region_id; ?>"]').attr('selected', 'selected');
                    });
                });
            </script>

            <!-- require for edit default shipping -->
            <script type="text/javascript">
                require([
                    'jquery',
                    'mage/mage'
                ], function ($) {
                    let dataForm = $('.form-address-edit#<?= $idAddress; ?>');
                    dataForm.mage('validation', {});
                });
            </script>
        <?php endif; ?>
    </div>
</div>

<?php
// address book
$addressBook = $_objectManager->get('Magento\Customer\Block\Address\Book');
?>
<?php if ($_pAddresses = $addressBook->getAdditionalAddresses()): ?>
    <?php foreach ($_pAddresses as $_address): ?>
        <?php $changeArray = array();
        $changeArray = $_address->__toArray();
        // echo "<pre>";print_r($changeArray);
        $idAddress = $changeArray['id'];
        $firstName = $changeArray['firstname'];
        $lastName = $changeArray['lastname'];
        $street = $changeArray['street'][0];
        if (isset($changeArray['street'][1])) {
            $street3 = $changeArray['street'][1];
        }
        $city = $changeArray['city'];
        $country_id = $changeArray['country_id'];
        $region_id = $changeArray['region_id'];
        $postcode = $changeArray['postcode'];
        $telephone = $changeArray['telephone'];
        $customer_id = $changeArray['customer_id'];
        ?>

        <div class="save-address">
            <div class="title-address">
                <a href="javascript:void(0)" class="link-edit-address"><?= __('Edit'); ?></a>
            </div>
            <div class="box-address">
                <div class="content-address">
                    <p><?= $addressBook->getAddressHtml($_address) ?></p>
                </div>
                <div class="content-edit-address">
                    <div class="box-edit-address">
                        <form class="form-address-edit" id="<?= $idAddress; ?>"
                              action="<?= $this->getBaseUrl(); ?>customer/address/formPost/id/<?= $idAddress; ?>/"
                              method="post" id="form-validate" enctype="multipart/form-data"
                              data-hasrequired="* Required Fields" novalidate="novalidate">
                            <?= $addressBook->getBlockHtml('formkey') ?>
                            <div class="content-details">
                                <div class="field field-firstname required">
                                    <label class="label" for="name">
                                        <span><?= __('name') ?></span>
                                    </label>
                                    <div class="control">
                                        <input type="text" id="name" name="firstname" value="<?= $firstName; ?>"
                                               title="Name"
                                               class="input-text required-entry" data-validate="{required:true}"
                                               aria-required="true">
                                    </div>
                                </div>
                            </div>
                            <div class="content-details">
                                <div class="field field-lastname required">
                                    <label class="label" for="lastname">
                                        <span><?= __('last name') ?></span>
                                    </label>
                                    <div class="control">
                                        <input type="text" id="lastname" name="lastname" value="<?= $lastName; ?>"
                                               title="Last Name"
                                               class="input-text required-entry" data-validate="{required:true}"
                                               aria-required="true">
                                    </div>
                                </div>
                            </div>
                            <div class="content-details">
                                <div class="field field-address required">
                                    <label class="label" for="address">
                                        <span><?= __('address') ?></span>
                                    </label>
                                    <div class="control">
                                        <input type="text" id="street_1" name="street[]" value="<?= $street; ?>"
                                               title="Address"
                                               class="input-text required-entry" data-validate="{required:true}"
                                               aria-required="true">
                                    </div>
                                    <?php if (isset($street3)): ?>
                                        <div class="control paddingtop">
                                            <input type="text" id="street_2" name="street[]" value="<?= $street3; ?>"
                                                   title="Street Address 2"
                                                   class="input-text required-entry" data-validate="{required:true}"
                                                   aria-required="true">
                                        </div>
                                    <?php else: ?>
                                        <div class="control paddingtop">
                                            <input type="text" id="street_2" name="street[]" value=""
                                                   title="Street Address 2"
                                                   class="input-text" data-validate="{required:false}"
                                                   aria-required="false">
                                        </div>
                                    <?php endif; ?>
                                </div>
                            </div>
                            <div class="content-details">
                                <div class="field field-city required">
                                    <label class="label" for="city">
                                        <span><?= __('city') ?></span>
                                    </label>
                                    <div class="control">
                                        <input type="text" id="city" name="city" value="<?= $city; ?>"
                                               title="City" class="input-text required-entry"
                                               data-validate="{required:true}"
                                               aria-required="true">
                                    </div>
                                </div>
                            </div>
                            <div class="book-state content-details lx-<?= $idAddress ?>">
                                <div class="field state">
                                    <label class="label" for="state">
                                        <span><?= __('state') ?></span>
                                    </label>
                                    <div class="control">
                                        <?= $regionList; ?>
                                    </div>
                                </div>
                            </div>
                            <div class="content-details zip-code">
                                <div class="field field-zip-code required">
                                    <label class="label" for="zipcode">
                                        <span><?= __('zip code') ?></span>
                                    </label>
                                    <div class="control">
                                        <input type="text" id="zip" name="postcode"
                                               value="<?= $postcode; ?>" title="zipcode"
                                               class="input-text validate-zip-international"
                                               data-validate="{required:true}"
                                               aria-required="true">
                                    </div>
                                </div>
                            </div>
                            <div class="content-details phone">
                                <div class="field field-phone required">
                                    <label class="label" for="phone">
                                        <span><?= __('phone') ?></span>
                                    </label>
                                    <div class="control">
                                        <input type="text" id="telephone" name="telephone" value="<?= $telephone; ?>"
                                               title="phone" class="input-text required-entry"
                                               data-validate="{required:true}"
                                               aria-required="true">
                                    </div>
                                </div>
                            </div>
                            <div class="content-details country">
                                <div class="field country">
                                    <label class="label" for="country">
                                        <span><?= __('country') ?></span>
                                    </label>
                                    <div class="control">
                                        <?= $countryList; ?>
                                    </div>
                                </div>
                            </div>
                            <div class="content-details edit_shipping_address">
                                <div class="checkbox-field">
                                    <input type="checkbox" id="primary_shipping" name="default_shipping" value="1"
                                           class="checkbox">
                                    <label for="primary_shipping"><span>Set as default address</span></label>
                                </div>
                            </div>

                            <div class="primary saved-box">
                                <button type="submit" class="action primary" title="<?= __('Save') ?>">
                                    <span><?= __('Save Changes') ?></span>
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>

        <script type="text/javascript">
            require(['jquery'], function ($) {
                $(function () {
                    // select state
                    // $(".book-state.content-details").find('option').removeAttr("selected");
                    $('.book-state.content-details.lx-<?= $idAddress; ?> .state #state option[value="<?= $region_id; ?>"]').attr('selected', 'selected');
                });
            });
        </script>

        <!-- require for edit book shipping -->
        <script type="text/javascript">
            require([
                'jquery',
                'mage/mage'
            ], function ($) {

                let dataForm = $('.form-address-edit#<?= $idAddress; ?>');
                dataForm.mage('validation', {});

            });
        </script>
    <?php endforeach; ?>
<?php endif; ?>

<!-- Add shipping address -->

<div class="save-address add-shipping-address">
    <div class="title-address">
        <span class="link-add-address"><?= __('+  '); ?><?= __('Add shipping address'); ?></span>
    </div>
    <div class="box-address">
        <div class="content-edit-address">
            <div class="box-edit-address">
                <form class="form" id="add-custom-form" method="post" autocomplete="off">
                    <div class="content-details">
                        <div class="field field-firstname required">
                            <label class="label" for="name">
                                <span><?= __('name') ?></span>
                            </label>
                            <div class="control">
                                <input type="text" id="name" name="firstname" value="" title="Name"
                                       class="input-text required-entry" data-validate="{required:true}"
                                       aria-required="true">
                            </div>
                        </div>
                    </div>
                    <div class="content-details">
                        <div class="field field-lastname required">
                            <label class="label" for="lastname">
                                <span><?= __('last name') ?></span>
                            </label>
                            <div class="control">
                                <input type="text" id="lastname" name="lastname" value="" title="Last Name"
                                       class="input-text required-entry" data-validate="{required:true}"
                                       aria-required="true">
                            </div>
                        </div>
                    </div>
                    <div class="content-details">
                        <div class="field field-address required">
                            <label class="label" for="address">
                                <span><?= __('address') ?></span>
                            </label>
                            <div class="control">
                                <input type="text" id="address" name="address" value="" title="Address"
                                       class="input-text required-entry" data-validate="{required:true}"
                                       aria-required="true">
                            </div>
                            <div class="control paddingtop">
                                <input type="text" id="address2" name="address2" value=""
                                       title="Street Address 2"
                                       class="input-text">
                            </div>
                        </div>
                    </div>
                    <div class="content-details">
                        <div class="field field-city required">
                            <label class="label" for="city">
                                <span><?= __('city') ?></span>
                            </label>
                            <div class="control">
                                <input type="text" id="city" name="city" value=""
                                       title="City" class="input-text required-entry" data-validate="{required:true}"
                                       aria-required="true">
                            </div>
                        </div>
                    </div>
                    <div class="content-details">
                        <div class="field state">
                            <label class="label" for="state">
                                <span><?= __('state') ?></span>
                            </label>
                            <div class="control">
                                <?= $regionList; ?>
                            </div>
                        </div>
                    </div>
                    <div class="content-details zip-code">
                        <div class="field field-zip-code required">
                            <label class="label" for="zipcode">
                                <span><?= __('zip code') ?></span>
                            </label>
                            <div class="control">
                                <input type="text" id="zipcode" name="zipcode"
                                       value="" title="zipcode"
                                       class="input-text required-entry" data-validate="{required:true}"
                                       aria-required="true">
                            </div>
                        </div>
                    </div>
                    <div class="content-details phone">
                        <div class="field field-phone required">
                            <label class="label" for="phone">
                                <span><?= __('phone') ?></span>
                            </label>
                            <div class="control">
                                <input type="text" id="phone" name="phone" value=""
                                       title="phone" class="input-text required-entry" data-validate="{required:true}"
                                       aria-required="true">
                            </div>
                        </div>
                    </div>
                    <div class="content-details country">
                        <div class="field country">
                            <label class="label" for="country">
                                <span><?= __('country') ?></span>
                            </label>
                            <div class="control">
                                <?= $countryList; ?>
                            </div>
                        </div>
                    </div>
                    <div class="content-details add_shipping_address">
                        <div class="checkbox-field">
                            <input type="checkbox" id="add_shipping" name="default_shipping" value="" class="checkbox">
                            <label for="add_shipping"><span>Set as default address</span></label>
                        </div>
                    </div>
                    <div class="primary">
                        <button type="submit" class="action save primary" title="<?= __('Save') ?>">
                            <span><?= __('Save Changes') ?></span>
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<?php
$resource = $_objectManager->get('Magento\Framework\App\ResourceConnection');
$connection = $resource->getConnection();
$tableName = $resource->getTableName('local_retailer_store');

$sql = "Select * FROM " . $tableName . " WHERE id_customer_use =" . $getCustomerId;
$array_customer = $connection->fetchAll($sql);
if (!empty($array_customer)) {
    foreach ($array_customer as $key) {
        $retailerId = $key['retailer_id'];
        break;
    } ?>

    <?php /**
     * <style type="text/css">
     *
     * <?= $retailerId; ?> .product-items .<?= $retailerId; ?> .make-this-store span {
     * display: none;
     * }
     *
     * <?= $retailerId; ?> .product-items .<?= $retailerId; ?> .location-radio .label {
     * display: block !important;
     * }
     * </style>
     **/ ?>
<?php }
?>
<div class="my-local-retailer" id="retailer-store">
    <div class="box-local-retailer">
        <div class="header-retailer">
            <span class="title"><?= __('My local retailer') ?></span>
            <p class="text-retails">We partner together with local infinity retailers to bring you this infinity site.
                Please share below who is doing a great job in your community so we can recognize them. We hope you
                visit your favorite infinity scrubs store soon!</p>
        </div>
        <div class="content-retailer">
            <span class="find">Find nearest store</span>
            <div class="content-details zip">
                <div class="field field-zip required">
                    <label class="label" for="zipcode">
                        <span><?= __('zip code') ?></span>
                    </label>
                    <div class="control">
                        <input type="text" id="zip" name="zip" value="" title="zip" placeholder="Zip or City, State"
                               class="input-text  input-zip" data-validate="{required:true}" aria-required="true">
                    </div>
                </div>
            </div>
            <span class="join-text"><?= __('within') ?></span>
            <div class="content-details distance">
                <div class="control select-control">
                    <select id="storeSelector" class="select">
                        <option value="">Please select a radius.</option>
                        <option value="5" data-title="5 miles">5 miles</option>
                        <option value="10" data-title="10 miles">10 miles</option>
                        <option value="20" data-title="20 miles">20 miles</option>
                        <option value="30" data-title="30 miles">30 miles</option>
                        <option value="40" data-title="40 miles">40 miles</option>
                        <option value="50" data-title="50 miles">50 miles</option>
                    </select>
                </div>
            </div>
            <a href="javascript:void(0)" id="finder-submit">
                <span class="join-text"><?= __('Submit') ?></span></a>
        </div>
        <div class="footer-retailer" id="<?php if (isset($retailerId)) {
            echo $retailerId;
        } ?>">
            <div class="products list items product-items the-bottom-slider">
                <?php
                if (!empty($array_customer)) {
                    $storeName = "";
                    $street = "";
                    $city = "";
                    $state = "";
                    $zip = "";
                    foreach ($array_customer as $key) {
                        $storeName = $key['store_name'];
                        $street = $key['street'];
                        $city = $key['city'];
                        $state = $key['state'];
                        $zip = $key['zip'];
                        break;
                    } ?>
                    <div class="location" style="width: 252px;" id="main-local-retails">
                        <div class="location-radio">
                            <label class="label" style="display: block;">MY LOCAL RETAILER</label>
                        </div>
                        <div class="location-body">
                            <div class="name-store"><?= $storeName; ?></div>
                            <?= $street; ?>,<br><?= $city; ?>, <?= $state; ?>, <?= $zip; ?><br>
                        </div>
                    </div>
                <?php } ?>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    require(['jquery'], function ($) {
        $(function () {
            let hash = window.location.hash;
            if (hash === "#defaultshipping") {

                $('#defaultshipping .link-edit-address').addClass('focus');
                $('#defaultshipping').addClass('active');
            }

            $('.link-edit-address').click(function (i) {
                if ($(this).hasClass("focus")) {
                    $(this).removeClass('focus');
                    $(this).parent().parent().removeClass('active');
                } else {
                    $(this).addClass('focus');
                    $(this).parent().parent().addClass('active');
                }
            });
        });
    });
</script>

<script type="text/javascript">
    require(['jquery'], function ($) {
        $(document.body).on('click', '.make-this-store span', function () {
            $('.make-this-store').removeClass('active');
            $(this).parent().addClass('active');
            let monday = "no", saturday = "no";
            let retailerId = $('.make-this-store.active .retailerid-retailer').val();
            let storeName = $('.make-this-store.active .storename-retailer').val();
            let street = $('.make-this-store.active .street-retailer').val();
            let city = $('.make-this-store.active .city-retailer').val();
            let state = $('.make-this-store.active .state-retailer').val();
            let zip = $('.make-this-store.active .zip-retailer').val();
            let distance = $('.make-this-store.active .distance-retailer').val();
            let phone = $('.make-this-store.active .phone-retailer').val();
            monday = $('.make-this-store.active .monday-retailer').val();
            saturday = $('.make-this-store.active .saturday-retailer').val();
            let getCusId = "";
            getCusId = <?= $getCustomerId ?>;

            jQuery.ajax({
                url: '<?= $this->getBaseUrl() . 'localretailer/load/load'?>',
                type: "POST",
                dataType: 'json',
                showLoader: true,
                data: {
                    retailerid: retailerId,
                    storename: storeName,
                    street: street,
                    city: city,
                    state: state,
                    zip: zip,
                    distance: distance,
                    phone: phone,
                    monday: monday,
                    saturday: saturday,
                    getidcus: getCusId
                },
                success: function (data) {
                    // location.reload();
                    let footerRetailer = $('.footer-retailer');
                    footerRetailer.removeAttr('id');
                    footerRetailer.attr('id', retailerId);
                    $(".customer-account-edit .column.main .my-local-retailer .box-local-retailer .footer-retailer .location .location-radio .label").removeAttr('style');
                    $(".customer-account-edit .column.main .my-local-retailer .box-local-retailer .footer-retailer .location." + retailerId + " .location-radio .label").css("display", "block");

                    $(".make-this-store span").removeAttr('style');
                    $(".make-this-store.active span").css("display", "none");
                }
            });
        });
    });
</script>

<!-- add new address -->
<script type="text/javascript">
    require(['jquery'], function ($) {
        $(function () {
            /**
             * @return null
             */
            $('.link-add-address').click(function () {
                if ($(this).hasClass("focus")) {
                    $(this).removeClass('focus');
                    $(this).text("+  Add shipping address");
                    $(this).parent().parent().removeClass('active');
                } else {
                    $(this).addClass('focus');
                    $(this).text("-  Add shipping address");
                    $(this).parent().parent().addClass('active');
                }
            });


            $(".add-shipping-address .action.save.primary").click(function () {
                let add_shipping_default = 0;
                if ($('#add_shipping').is(":checked")) {
                    add_shipping_default = 1;
                }
                let name = $('.add-shipping-address .box-edit-address #name').val();
                let lastName = $('.add-shipping-address .box-edit-address #lastname').val();
                let address = $('.add-shipping-address .box-edit-address #address').val();
                let address2 = $('.add-shipping-address .box-edit-address #address2').val();
                let city = $('.add-shipping-address .box-edit-address #city').val();
                let phone = $('.add-shipping-address .box-edit-address #phone').val();
                let zipCode = $('.add-shipping-address .box-edit-address #zipcode').val();
                let state = $(".add-shipping-address .box-edit-address #state").val();
                let country = $(".add-shipping-address .box-edit-address #country").val();
                let getCusId = "";
                getCusId = <?= $getCustomerId ?>;
                if (state !== '') {
                    jQuery.ajax({
                        url: '<?= $this->getBaseUrl() . 'localretailer/book/book'?>',
                        type: "POST",
                        dataType: 'json',
                        showLoader: true,
                        data: {
                            name: name,
                            lastname: lastName,
                            address: address,
                            address2: address2,
                            city: city,
                            phone: phone,
                            zipcode: zipCode,
                            state: state,
                            country: country,
                            customer_id: getCusId,
                            add_shipping_default: add_shipping_default
                        },
                        success: function (data) {
                            // location.reload();
                        }
                    });
                }
            });
        });
    });
</script>

<!-- require for add address shipping -->
<script type="text/javascript">
    require([
        'jquery',
        'mage/mage'
    ], function ($) {

        let dataForm = $('#add-custom-form');
        dataForm.mage('validation', {});

    });
</script>