<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
?>
<?php
/** @var $block \Magento\Framework\View\Element\Template */
/** @var $helper \Magento\Search\Helper\Data */
$helper = $this->helper(\Magento\Search\Helper\Data::class);
?>

<div class="block block-search">
    <?php /**
     * <div class="block block-title"><strong><?= __('Search') ?></strong></div>
     **/ ?>

    <i class="search-icon icon-elo-search"></i>
    <div class="block block-content" style="display: none;">
        <form class="form minisearch" id="search_mini_form" action="<?= $helper->getResultUrl() ?>" method="get">
            <div class="field search">

                <label class="label" for="search" data-role="minisearch-label" style="display: none">
                    <span>Search</span>
                </label>

                <div class="control">
                    <input id="search"
                           data-mage-init='{"quickSearch":{
                            "formSelector":"#search_mini_form",
                            "url":"<?= $helper->getSuggestUrl() ?>",
                            "destinationSelector":"#search_autocomplete"}}'
                           type="text"
                           name="<?= $helper->getQueryParamName() ?>"
                           value="<?= $helper->getEscapedQueryText() ?>"
                           placeholder="<?= __('Search products here...') ?>"
                           class="input-text"
                           maxlength="<?= $helper->getMaxQueryLength() ?>"
                           role="combobox"
                           aria-haspopup="false"
                           aria-autocomplete="both"
                           autocomplete="on"/>
                    <div id="search_autocomplete" class="search-autocomplete"></div>
                    <?php /** $block->getChildHtml() **/ ?>
                </div>
            </div>

            <div class="actions">
                <button type="submit" title="Search" class="action search">
                    <span>Search</span>
                </button>
            </div>

        </form>
    </div>
</div>
