<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile
//"swatchRenderer": {
?>

<?php /** @var $block \Magento\Swatches\Block\Product\Renderer\Configurable */

//$helper = $this->helper('BinaryAnvil\SizeChart\Helper\Image');
//$attributeName = $helper->showInAttribute();

$product = $block->getProduct();
$curCat = $product->getCategory();

if (!$curCat) {
    $catIds = $product->getCategoryIds();
    if (is_array($catIds)) {
        $catIds = reset($catIds);
    }
//    if ($catIds) {
//        // $curCat = $helper->getCategoryById($catIds);
//    }
}

?>
<div class="swatch-opt" data-role="swatch-options"></div>

<!-- category object: <?= get_class($curCat); ?> -->
<?php if ($curCat) { ?>
    <div class="size-chart" style="display: none">
        <div class="size-chart-inner">
            <?= $curCat->getData('category_size_chart') ?>
            <div class="size-chart-close">
                <span class="far fa-times" id="closeSizeChart"></span>
            </div>
        </div>
    </div>
<?php } ?>

<script type="text/x-magento-init">
    {
        "[data-role=swatch-options]": {
            "Magento_Swatches/js/swatch-renderer": {
                "jsonConfig": <?= $swatchOptions = $block->getJsonConfig() ?>,
                "jsonSwatchConfig": <?= $block->getJsonSwatchConfig(); ?>,
                "mediaCallback": "<?= $block->getMediaCallback() ?>",
                "gallerySwitchStrategy": "<?= $block->getVar('gallery_switch_strategy',
        'Magento_ConfigurableProduct') ?: 'replace'; ?>"
            },
            "Magento_Swatches/js/configurable-customer-data": {
                    "swatchOptions": <?= $swatchOptions ?>
            }
        }
    }


</script>

