<?php

/** @var Lexim\Override\Block\Magento\Customer\Customer $block */

// Get sub total
$subTotal = $block->getSubTotal();
$check = 124.99 - (float) $subTotal;
$check = round($check, 2);

// Get User name
$firstName = "You";

if ($block->customerLoggedIn()) {
    $a = $block->getCurrentCustomer();
    $firstName = $a->getFirstname() . ", you";
}
?>

<?php if ($check > 0) { ?>

<div class="cart-check-free-shipping">
  <p><?= $firstName ?> are only $<span><?= $check ?></span> away from free shipping!</p>
</div>

<?php } ?>

