<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile
//"swatchRenderer": {
?>

<?php /** @var $block \Magento\Swatches\Block\Product\Renderer\Configurable */

/** @var BinaryAnvil\SizeChart\Helper\Image $helper */
$helper = $this->helper('BinaryAnvil\SizeChart\Helper\Image');
$attributeName = $helper->showInAttribute();

$product = $block->getProduct();
$curCat = $product->getCategory();

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
/** @var Magento\Catalog\Model\Product $_product */
$_product = $objectManager->create('\Magento\Catalog\Model\Product')->load($product->getId());

$catIds = $_product->getCategoryIds();
$catId = reset($catIds);
if ($catId) {
    $curCat = $helper->getCategoryById($catId);
}

?>
<div class="swatch-opt" data-role="swatch-options"></div>

<?php

if ($curCat) { ?>
    <div class="size-chart" style="display: none">
        <div class="size-chart-inner">
            <?= $curCat->getData('category_size_chart') ?>
            <div class="size-chart-close">
                <span class="far fa-times" id="closeSizeChart"></span>
            </div>
        </div>
    </div>
<?php }  ?>

<script type="text/x-magento-init">
    {
        "[data-role=swatch-options]": {
            "Magento_Swatches/js/swatch-renderer": {
                "jsonConfig": <?= $swatchOptions = $block->getJsonConfig() ?>,
                "jsonSwatchConfig": <?= $block->getJsonSwatchConfig(); ?>,
                "mediaCallback": "<?= $block->getMediaCallback() ?>",
                "gallerySwitchStrategy": "<?= $block->getVar('gallery_switch_strategy',
        'Magento_ConfigurableProduct') ?: 'replace'; ?>"
            },
            "Magento_Swatches/js/configurable-customer-data": {
                    "swatchOptions": <?= $swatchOptions ?>
            }
        }
    }

</script>

